require("angel")
.sh()
    .send("git pull")
    .send("git push")
.exit()
.ssh()
    .send("cd ~/project/backend")
    .send("git pull")
    .send(". ~/.nvm/nvm.sh; nvm use v0.4.11")
    .send("npm install -d")
    .send("forever stop app.js")
    .send("forever start -o app-output.log -e app-error.log app.js")
.exit()
.export(module)
